<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(1,1,1,'5YWs5Y+4566A5LuL');
$cfg_Cs[3]=array(1,1,1,'5LyB5Lia5paH5YyW');
$cfg_Cs[4]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[5]=array(4,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[6]=array(4,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[7]=array(0,1,1,'5Lia5Yqh6IyD5Zu0');
$cfg_Cs[8]=array(7,1,1,'5oqV6LWE6aG555uu');
$cfg_Cs[9]=array(0,1,1,'5Lq65Yqb6LWE5rqQ');
$cfg_Cs[10]=array(9,1,1,'57uE57uH5p625p6E');
$cfg_Cs[11]=array(9,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[12]=array(0,1,1,'6IGU57O75oiR5Lus');
?>