<li><div class="nlist_l"><img src="[field:litpic/]" width="218" height="138"></div>
                    	<div class="nlist_r">
                        	<div class="nlist_r1"><a href="[field:arcurl/]" target="_blank" > [field:title/]</a></div>
                        	<div class="nlist_r2">[[field:pubdate function='strftime("%Y-%m-%d",@me)'/]]</div>
                        	<div class="nlist_r3"><p>[field:description function='cn_substr(@me,200)'/]...</p>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </li>