<li>
                	<div class="main2_b_t">
                    	<a href="[field:arcurl/]" target="_blank" >[field:title/]</a>
                    </div>
                    <div class="main2_b_c">
                    	<p>[field:description function='cn_substr(@me,100)'/]...</p>
                    </div>
                    <div class="main2_b_b">
                    	<a href="[field:arcurl/]" target="_blank" >查看详细</a>
                    </div>
                </li>