<?php
$z[0]=Array("global","",230,251);
$z[0][4]['name']="cfg_dz";
$z[1]=Array("global","",289,310);
$z[1][4]['name']="cfg_dh";
$z[2]=Array("global","",348,369);
$z[2][4]['name']="cfg_yx";
$z[3]=Array("global","",1423,1449);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",1464,1488);
$z[4][4]['name']="cfg_beian";
$z[5]=Array("flink","\r\n                           [field:link /]\r\n                           ",1966,2109);
$z[5][4]['titlelen']="50";
$z[5][4]['row']="20";
$z[5][4]['type']="text";
$z[5][4]['typeid']="2";
$z[6]=Array("flink","\r\n                           [field:link /]\r\n                           ",2368,2511);
$z[6][4]['titlelen']="50";
$z[6][4]['row']="20";
$z[6][4]['type']="text";
$z[6][4]['typeid']="1";

?>