<?php
$z[0]=Array("global","",170,196);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",248,278);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",323,350);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1022,1057);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n                <li>\r\n                	<div class=\"main2_b_t\">\r\n                    	<a href=\"[field:arcurl/]\" target=\"_blank\" >[field:title/]</a>\r\n                    </div>\r\n                    <div class=\"main2_b_c\">\r\n                    	<p>[field:description function='cn_substr(@me,100)'/]...</p>\r\n                    </div>\r\n                    <div class=\"main2_b_b\">\r\n                    	<a href=\"[field:arcurl/]\" target=\"_blank\" >查看详细</a>\r\n                    </div>\r\n                </li>\r\n            ",4719,5305);
$z[4][4]['row']="9";
$z[4][4]['titlelen']="30";
$z[4][4]['typeid']="4";
$z[5]=Array("include","",5709,5744);
$z[5][4]['filename']="foot.htm";

?>